services:
  db:
    image: postgres:alpine
    hostname: killjoy_db
    restart: on-failure
    expose:
      - 5432
    environment:
      POSTGRES_USERNAME: DB_USERNAME
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_DB: DB_NAME
    volumes:
      - killjoy-data:/var/lib/postgresql/data

  bot:
    image: blademaker/killjoy
    volumes:
      - ./credentials.conf:/app/credentials.conf:ro
      - killjoy-logs:/app/logs
    restart: on-failure
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 128M

volumes:
  killjoy-logs:
    external: true
  killjoy-data: { }
