version: "3.9"

services:
  bot:
    container_name: killjoy-bot
    image: blademaker/killjoy:latest
    volumes:
      - killjoy_config:/app/config:ro
      - killjoy_logs:/app/logs
    restart: on-failure
    network_mode: host

volumes:
  killjoy_config:
    external: true
  killjoy_logs:
    external: true