services:
  db:
    image: postgres:alpine
    hostname: killjoy_db
    restart: on-failure
    expose:
      - 5432
    environment:
      POSTGRES_USER: killjoy
      POSTGRES_PASSWORD: killjoy
      POSTGRES_DB: killjoy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - killjoy-data:/var/lib/postgresql/data

  bot:
    image: blademaker/killjoy
    volumes:
      - ./credentials.conf:/app/credentials.conf:ro
      - killjoy-logs:/app/logs
    restart: on-failure
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 128M

volumes:
  killjoy-logs:
    external: true
  killjoy-data: { }
