version: "3.9"

services:
  bot:
    image: blademaker/killjoy
    volumes:
      - ./credentials.conf:/app/credentials.conf:ro
      - killjoy-logs:/app/logs
    network_mode: host
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 128M

volumes:
  killjoy-logs:
    external: true
