version: "3.9"

services:
  bot:
    container_name: killjoy-bot
    image: blademaker/killjoy
    volumes:
      - ./credentials.conf:/app/credentials.conf:ro
      - killjoy-logs:/app/logs
    restart: on-failure
    network_mode: host

volumes:
  killjoy-logs:
    external: true
