name: Build and Publish Docker Container Image.

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to GitHub Container Registry
      run: |
        echo $CR_PAT | docker login ghcr.io -u Blad3Mak3r --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/blad3mak3r/killjoy:latest
        
    - name: Publish Container Image
      run: docker push ghcr.io/blad3mak3r/killjoy:latest
